### PR TITLE
Added functionality to edit/delete users

### PR DESCRIPTION
**Pull request by aamathur02**

### CODE REVIEW

**Review by JamesNarayanan — APPROVED** [review]
Code looks good, could use better commit names in the future

**Review by pnav1 — APPROVED** [review]
Looks good - love the snackbar

**Comment by JGOOCH1823** [comment]
Seems like everything is good to go!

**Review by rishiganesh2002 — APPROVED** [review]
Really great use of the snack-bars, the UI now looks great!

**Review by JGOOCH1823 — APPROVED** [review]
Appears that the changes are both consistent in style and efficient in functionality

**Review by ssraikhelkar — APPROVED** [review]
Seems solid, though for some reason deletes don't seem to be working. Will look into it on the database-side.

**Pull request merged**
